######################################################################
# Automatically generated by qmake (3.0) Tue Sep 1 19:33:36 2015
######################################################################

TEMPLATE = app
TARGET = FindDialog
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
