######################################################################
# Automatically generated by qmake (3.0) Tue Sep 1 21:37:50 2015
######################################################################

TEMPLATE = app
TARGET = GoToCell
INCLUDEPATH += .
QT += widgets
# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
