######################################################################
# Automatically generated by qmake (3.0) Wed Sep 2 00:56:22 2015
######################################################################

TEMPLATE = app
TARGET = GoToCell
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
