######################################################################
# Automatically generated by qmake (3.0) Wed Sep 2 17:11:09 2015
######################################################################

TEMPLATE = app
TARGET = Sort
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
